setwd("C:/Users/beaub/Research/Machine learning/Code for Sharing/1 Data cleaning")
source(paste(getwd(),"load_data.R",sep="/"))
setwd("C:/Users/beaub/Research/Machine learning/Code for Sharing/1 Data cleaning")
source(paste(getwd(),"merge_data.R",sep="/"))
setwd("C:/Users/beaub/Research/Machine learning/Code for Sharing/1 Data cleaning")
source(paste(getwd(),"extend_compustat_data.R",sep="/"))
setwd("C:/Users/beaub/Research/Machine learning/Code for Sharing/1 Data cleaning")
source(paste(getwd(),"link_dealscan_fundq_with_dates.R",sep="/"))
setwd("C:/Users/beaub/Research/Machine learning/Code for Sharing/1 Data cleaning")
source(paste(getwd(),"collect_processed_data.R",sep="/"))

setwd("C:/Users/beaub/Research/Machine learning/Code for Sharing/2 Different samples")
source(paste(getwd(),"NWallall.R",sep="/"))
setwd("C:/Users/beaub/Research/Machine learning/Code for Sharing/2 Different samples")
source(paste(getwd(),"NWallnoloan.R",sep="/"))
setwd("C:/Users/beaub/Research/Machine learning/Code for Sharing/2 Different samples")
source(paste(getwd(),"NWdefaultersall.R",sep="/"))
setwd("C:/Users/beaub/Research/Machine learning/Code for Sharing/2 Different samples")
source(paste(getwd(),"NWdefaultersnoloan.R",sep="/"))
setwd("C:/Users/beaub/Research/Machine learning/Code for Sharing/2 Different samples")
source(paste(getwd(),"CRallnoloan.R",sep="/"))
setwd("C:/Users/beaub/Research/Machine learning/Code for Sharing/2 Different samples")
source(paste(getwd(),"Bothallnoloan.R",sep="/"))

setwd("C:/Users/beaub/Research/Machine learning/Code for Sharing/3 Estimate causal forests")
source(paste(getwd(),"CRallnoloan_cf.R",sep="/"))
setwd("C:/Users/beaub/Research/Machine learning/Code for Sharing/3 Estimate causal forests")
source(paste(getwd(),"Bothallnoloan_cf.R",sep="/"))
